extends SceneTree
const EXPECTED = "C:/Users/freer/ClaudeProject/make-passive-income/reviews/games-2026-09-12/runtime/npc-villager-runtime-v1/userdata/NpcVillagerRuntime"
var passed := 0
var failed := 0
func _initialize(): call_deferred("run")
func check(ok, text):
	if ok: passed += 1
	else: failed += 1
	print("[PASS] " if ok else "[FAIL] ",text)
func run():
	if OS.get_user_data_dir().replace("\\", "/") != EXPECTED:
		quit(1)
		return
	if "--probe" in OS.get_cmdline_user_args():
		print("NPC_RUNTIME_PROBE_EXACT=",EXPECTED)
		quit(0)
		return
	var quest = root.get_node("QuestSystem")
	var events = root.get_node("Events")
	var csv := FileAccess.open("res://localization/ui_ko.csv",FileAccess.READ)
	var translation := Translation.new()
	translation.locale = "ko"
	csv.get_csv_line()
	while not csv.eof_reached():
		var row := csv.get_csv_line()
		if row.size() == 2: translation.add_message(row[0],row[1])
	TranslationServer.add_translation(translation)
	TranslationServer.set_locale("ko")
	var hud_scene = load("res://scenes/ui/Hud.tscn").instantiate()
	root.add_child(hud_scene)
	var hud = hud_scene.get_node("Root")
	await process_frame
	for npc in [&"pinto",&"rozel",&"dami"]:
		for i in range(4):
			events.npc_talked.emit(npc)
			var label = hud.log_list.get_child(hud.log_list.get_child_count()-1)
			check(label.text == translation.get_message("npc.%s.everyday.%d" % [npc,i%3+1]),"actual HUD event cycle "+String(npc))
	quest.from_dict({"completed":["quest_side_heartland_montsil"]})
	var snapshot = quest.to_dict().duplicate(true)
	for i in range(4):
		events.npc_talked.emit(&"dami")
		var label = hud.log_list.get_child(hud.log_list.get_child_count()-1)
		check(label.text == translation.get_message("npc.dami.after_montsil.%d" % (i%3+1)),"actual completed quest selects Dami group")
	check(quest.to_dict() == snapshot,"greetings do not change completed quest state")
	events.npc_talked.emit(&"unknown")
	check(hud.log_list.get_child(hud.log_list.get_child_count()-1).text == "npc.unknown.greeting","actual HUD unknown fallback")
	check(not FileAccess.file_exists("user://saves/slot0_auto.json"),"no autosave generated by greetings")
	print("NPC_RUNTIME_RESULT PASS=",passed," FAIL=",failed)
	hud_scene.queue_free()
	TranslationServer.remove_translation(translation)
	await process_frame
	quit(0 if failed == 0 else 1)
