extends SceneTree
var passed := 0
var failed := 0
func _initialize(): call_deferred("run")
func check(ok, text):
	if ok: passed += 1
	else: failed += 1
	print("[PASS] " if ok else "[FAIL] ", text)
func run():
	if OS.get_user_data_dir().replace("\\", "/") != OS.get_environment("NPC_EXPECTED_USER_DIR"):
		quit(1)
		return
	var quest = root.get_node("QuestSystem")
	var events = root.get_node("Events")
	# CSV is an independent expected-value oracle, never injected into TranslationServer.
	var csv := FileAccess.open("res://localization/ui_ko.csv", FileAccess.READ)
	var expected := {}
	csv.get_csv_line()
	while not csv.eof_reached():
		var row := csv.get_csv_line()
		if row.size() == 2: expected[row[0]] = row[1]
	TranslationServer.set_locale("ko")
	check("ko" in TranslationServer.get_loaded_locales(), "project imported Korean locale loaded")
	check(expected.size() == 236, "exact 236 CSV keys retained")
	for key in expected:
		check(TranslationServer.translate(key) == expected[key], "all imported CSV keys: " + key)
	for npc in ["pinto", "rozel", "dami"]:
		for group in (["everyday", "after_montsil"] if npc == "dami" else ["everyday"]):
			for i in range(1, 4):
				var key = "npc.%s.%s.%d" % [npc, group, i]
				check(TranslationServer.translate(key) == expected[key], "imported translation matches CSV: " + key)
	var hud_scene = load("res://scenes/ui/Hud.tscn").instantiate()
	root.add_child(hud_scene)
	var hud = hud_scene.get_node("Root")
	await process_frame
	var initial = quest.to_dict().duplicate(true)
	for npc in [&"pinto", &"rozel", &"dami", &"teo", &"meru"]:
		for i in range(4):
			events.npc_talked.emit(npc)
			var label = hud.log_list.get_child(hud.log_list.get_child_count() - 1)
			check(label.text == expected["npc.%s.everyday.%d" % [npc, i % 3 + 1]], "actual HUD event cycle " + String(npc))
	check(quest.to_dict() == initial, "idle greetings preserve initial quest state")
	# Fixture completion, not a gameplay completion claim.
	quest.from_dict({"completed": ["quest_side_heartland_montsil", "quest_main_a1_06_echocave"]})
	var snapshot = quest.to_dict().duplicate(true)
	for npc in [&"dami", &"teo", &"meru"]:
		var group = "after_montsil" if npc == &"dami" else "after_cave"
		for i in range(4):
			events.npc_talked.emit(npc)
			var label = hud.log_list.get_child(hud.log_list.get_child_count() - 1)
			check(label.text == expected["npc.%s.%s.%d" % [npc, group, i % 3 + 1]], "actual completed quest group " + String(npc))
	check(quest.to_dict() == snapshot, "greetings preserve completed quest state")
	events.npc_talked.emit(&"unknown")
	check(hud.log_list.get_child(hud.log_list.get_child_count() - 1).text == "npc.unknown.greeting", "actual HUD unknown fallback")
	check(not FileAccess.file_exists("user://saves/slot0_auto.json"), "no autosave generated by greetings")
	print("NPC_RUNTIME_IMPORTED_RESULT PASS=", passed, " FAIL=", failed)
	hud_scene.queue_free()
	await process_frame
	quit(0 if failed == 0 else 1)
